### ISSUE TITLE
correct_periscope_drift sherpa plotting changes

### ISSUE THREAD

**Issue by kglotfelty** [cxcsds/ciao-contrib#579] opened 2022-02-02 12:36 UTC
In this week's CIAOX build (2022-02-01), we are getting an error in `correct_periscope_drift`

`# correct_periscope_drift (6 Feb 2020): ERROR module 'sherpa.plot' has no attribute 'exceptions'`

Sherpa introduced some changes to plotting in this week's build, but I'm not sure which would have introduced this change.

We need to update the script for whatever plotting changes sherpa makes (both short and long term) . @DougBurke or @hamogu do you have any suggestions for a short term fix?

**Comment by DougBurke** [comment] 2022-02-02 13:34
So, the problem is in 

https://github.com/cxcsds/ciao-contrib/blob/242c760dcb6d19c82eb8e944c670d2fc43356303/bin/correct_periscope_drift#L374-L378

and there's something similar in the next routine.

You should be able to change `plot.exceptions()` to `plot.backend.exceptions()`. I'm about 90% sure that'll work.

**Comment by DougBurke** [comment] 2022-02-02 13:38
I think that this change should be backwards compatible, but I'm less sure about that...

**Comment by hamogu** [comment] 2022-02-02 13:43
I was not aware that ciao-contrib is digging that deep into sherpa
plotting details. Doug's suggested fix should work (now and long-term).
I will review ciao-contrib plotting code but I see a few more instances
of "instead of using sherpa plotting code, let's just change this
manually." I'll have to look which of those are (or will be) affected.
The goal of the sherpa plotting changes is to keep changes to the
documented API to a minimum, I had hoped I would have more liberty in
the inner layers of the sherpa plotting backends. I guess much of this
code was written by Doug, who was aware of all the classes in the grey
zone that are neither documented not technically marked as internal.

**Comment by hamogu** [comment] 2022-02-02 13:44
It's backwards compatible.

**Comment by hamogu** [comment] 2022-02-02 13:53
I'll do a PR later today for this and a few other occurrences.

**Comment by kglotfelty** [comment] 2022-02-07 15:29
@jeanconn , FYI

**Closed** 2022-11-04 14:12 UTC
